const PRODUCTS = [
  {
    id: 1,
    name: "Apple",
    description: "Apple",
    img: "Apple.jpg",
    price: 100,
    tags: ["fruits"],
  },
  {
    id: 2,
    name: "Milk",
    description: "Milk",
    img: "Milk.jpg",
    price: 100,
    tags: ["dairy"],
  },
  {
    id: 3,
    name: "Banana",
    description: "Banana",
    img: "Banana.jpg",
    price: 100,
    tags: ["fruits"],
  },
  {
    id: 4,
    name: "cabbage",
    description: "cabbage",
    img: "Cabbage.jpg",
    price: 100,
    tags: ["veg"],
  },
  {
    id: 5,
    name: "carrot",
    description: "carrot",
    img: "Carrot.jpg",
    price: 100,
    tags: ["veg"],
  },
  {
    id: 6,
    name: "keera",
    description: "French keera",
    img: "Keera.jpg",
    price: 70,
    tags: ["veg"],
  },
  {
    id: 7,
    name: "Orange",
    description: "Orange",
    img: "Orange.jpg",
    price: 114,
    tags: ["fruits"],
  },
  {
    id: 8,
    name: "Sapota",
    description: "Supota",
    img: "Sapota.jpg",
    price: 125,
    tags: ["fruits"],
  },
  {
    id: 9,
    name: "Grapes",
    description: "Grapes",
    img: "Grapes.jpg",
    price: 80,
    tags: ["fruits"],
  },
  {
    id: 10,
    name: "Cheese",
    description: "Cheese",
    img: "Cheese.jpg",
    price: 200,
    tags: ["dairy"],
  },
];

export default PRODUCTS;
